<?php
$GLOBALS['plugin']->addPermission("Browser structure", array(
"addNode",
"exitSaveNode",
"exitNode",
"ctrlCancel",
"cutNode",
"copyNode",
"insertNode",
"addFirstNode",
"saveNode",
"editNode",
"editNodePerms",
"moveNodeDown",
"moveNodeUp",
"deleteNode",
"addFolderConfirmAndNew",
"effectRotateRight",
"addFolder",
"effectRotateLeft",
"addFolderConfirm",
"getSelection",
"deleteNodeImage"
));
?>