<?php
$GLOBALS['plugin']->addPermission('Edit events',array(
'editNode', 
'deleteEvent', 
'editEvent', 
'deactivateLang', 
'editNodePerms', 
'activateLang', 
'deleteNode', 
'cutEntry', 
'deactivate', 
'ctrlCancel',
'insertNode',
'activate',
'copyNode',
'cutNode',
'insertEntry',
'copyEntry',
'saveEventAndClose', 
'saveEvent', 
'saveNode'
));
?>