<?php
$GLOBALS['plugin']->addPermission('Edit News', array(
                                                    'editNews',
                                                    'saveNews',
                                                    'copyChapter',
                                                    'cuttedChapter',
                                                    'addChapter',
                                                    'deleteChapter',
                                                    'activateChapter',
                                                    'deactivateChapter',
                                                    'deleteImage',
                                                    'saveSingle',
                                                    'saveNewsAndPreview',
                                                    'deleteChapterImage',
                                                    'cutChapter',
                                                    'copyChapter',
                                                    'saveNewsAndClose',
                                                    'saveNewsAndPublish',
                                                    'close',
                                                    'copyToLang',
                                                    'generateFeeds',
                                                    ));
?>